name: wrangler deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: wrangler production deployment
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@v4

      - name: setup bun environment
        uses: oven-sh/setup-bun@v2

      - name: install project deps
        run: bun install --frozen-lockfile

      - name: building client
        run: bun run build

      - name: deploying workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}
          accountId: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          secrets: |
            DATABASE_URL
            BETTER_AUTH_SECRET
            BETTER_AUTH_URL
            GOOGLE_OAUTH_CLIENT_ID
            GOOGLE_OAUTH_CLIENT_SECRET
          packageManager: bun
          wranglerVersion: 4.50.0
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          BETTER_AUTH_SECRET: ${{secrets.BETTER_AUTH_SECRET}}
          BETTER_AUTH_URL: ${{secrets.BETTER_AUTH_URL}}
          GOOGLE_OAUTH_CLIENT_ID: ${{secrets.GOOGLE_OAUTH_CLIENT_ID}}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{secrets.GOOGLE_OAUTH_CLIENT_SECRET}}
